//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int ID_DETALLE { get; set; }
        public int ID_FACTURA { get; set; }
        public int CODIGO_PARTIDO { get; set; }
        public string CODIGO_LOCALIDAD { get; set; }
        public int BOLETOS_VENDIDOS { get; set; }
        public decimal TOTAL_RECAUDADO { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
    }
}
