//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monster.Edu.Ec.Federacion.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FederacionFutbolDBEntities : DbContext
    {
        public FederacionFutbolDBEntities()
            : base("name=FederacionFutbolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOCALIDAD_PARTIDO> LOCALIDAD_PARTIDO { get; set; }
        public virtual DbSet<PARTIDO_FUTBOL> PARTIDO_FUTBOL { get; set; }
    }
}
