//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monster.Edu.Ec.Federacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDAD_PARTIDO
    {
        public int CODIGO_PARTIDO { get; set; }
        public string CODIGO_LOCALIDAD { get; set; }
        public int DISPONIBILIDAD { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual PARTIDO_FUTBOL PARTIDO_FUTBOL { get; set; }
    }
}
