//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monster.Edu.Ec.Federacion.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDO_FUTBOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIDO_FUTBOL()
        {
            this.LOCALIDAD_PARTIDO = new HashSet<LOCALIDAD_PARTIDO>();
        }
    
        public int CODIGO { get; set; }
        public string EQUIPO_LOCAL { get; set; }
        public string EQUIPO_VISITA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string LUGAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCALIDAD_PARTIDO> LOCALIDAD_PARTIDO { get; set; }
    }
}
