//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPremium.WCF.FederacionWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidoDTO", Namespace="http://schemas.datacontract.org/2004/07/Monster.Edu.Ec.Federacion.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class PartidoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoVisitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoLocal {
            get {
                return this.EquipoLocalField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoLocalField, value) != true)) {
                    this.EquipoLocalField = value;
                    this.RaisePropertyChanged("EquipoLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipoVisita {
            get {
                return this.EquipoVisitaField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoVisitaField, value) != true)) {
                    this.EquipoVisitaField = value;
                    this.RaisePropertyChanged("EquipoVisita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lugar {
            get {
                return this.LugarField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarField, value) != true)) {
                    this.LugarField = value;
                    this.RaisePropertyChanged("Lugar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalidadDTO", Namespace="http://schemas.datacontract.org/2004/07/Monster.Edu.Ec.Federacion.WCF.Models")]
    [System.SerializableAttribute()]
    public partial class LocalidadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisponibilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLocalidad {
            get {
                return this.CodigoLocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLocalidadField, value) != true)) {
                    this.CodigoLocalidadField = value;
                    this.RaisePropertyChanged("CodigoLocalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Disponibilidad {
            get {
                return this.DisponibilidadField;
            }
            set {
                if ((this.DisponibilidadField.Equals(value) != true)) {
                    this.DisponibilidadField = value;
                    this.RaisePropertyChanged("Disponibilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FederacionWS.IFederacionService")]
    public interface IFederacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/ObtenerPartidosDisponibles", ReplyAction="http://tempuri.org/IFederacionService/ObtenerPartidosDisponiblesResponse")]
        TicketPremium.WCF.FederacionWS.PartidoDTO[] ObtenerPartidosDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/ObtenerPartidosDisponibles", ReplyAction="http://tempuri.org/IFederacionService/ObtenerPartidosDisponiblesResponse")]
        System.Threading.Tasks.Task<TicketPremium.WCF.FederacionWS.PartidoDTO[]> ObtenerPartidosDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/ObtenerLocalidadesDisponibles", ReplyAction="http://tempuri.org/IFederacionService/ObtenerLocalidadesDisponiblesResponse")]
        TicketPremium.WCF.FederacionWS.LocalidadDTO[] ObtenerLocalidadesDisponibles(int codigoPartido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/ObtenerLocalidadesDisponibles", ReplyAction="http://tempuri.org/IFederacionService/ObtenerLocalidadesDisponiblesResponse")]
        System.Threading.Tasks.Task<TicketPremium.WCF.FederacionWS.LocalidadDTO[]> ObtenerLocalidadesDisponiblesAsync(int codigoPartido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/DisminuirDisponibilidad", ReplyAction="http://tempuri.org/IFederacionService/DisminuirDisponibilidadResponse")]
        bool DisminuirDisponibilidad(int codigoPartido, string codigoLocalidad, int boletosComprados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFederacionService/DisminuirDisponibilidad", ReplyAction="http://tempuri.org/IFederacionService/DisminuirDisponibilidadResponse")]
        System.Threading.Tasks.Task<bool> DisminuirDisponibilidadAsync(int codigoPartido, string codigoLocalidad, int boletosComprados);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFederacionServiceChannel : TicketPremium.WCF.FederacionWS.IFederacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FederacionServiceClient : System.ServiceModel.ClientBase<TicketPremium.WCF.FederacionWS.IFederacionService>, TicketPremium.WCF.FederacionWS.IFederacionService {
        
        public FederacionServiceClient() {
        }
        
        public FederacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FederacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FederacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FederacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TicketPremium.WCF.FederacionWS.PartidoDTO[] ObtenerPartidosDisponibles() {
            return base.Channel.ObtenerPartidosDisponibles();
        }
        
        public System.Threading.Tasks.Task<TicketPremium.WCF.FederacionWS.PartidoDTO[]> ObtenerPartidosDisponiblesAsync() {
            return base.Channel.ObtenerPartidosDisponiblesAsync();
        }
        
        public TicketPremium.WCF.FederacionWS.LocalidadDTO[] ObtenerLocalidadesDisponibles(int codigoPartido) {
            return base.Channel.ObtenerLocalidadesDisponibles(codigoPartido);
        }
        
        public System.Threading.Tasks.Task<TicketPremium.WCF.FederacionWS.LocalidadDTO[]> ObtenerLocalidadesDisponiblesAsync(int codigoPartido) {
            return base.Channel.ObtenerLocalidadesDisponiblesAsync(codigoPartido);
        }
        
        public bool DisminuirDisponibilidad(int codigoPartido, string codigoLocalidad, int boletosComprados) {
            return base.Channel.DisminuirDisponibilidad(codigoPartido, codigoLocalidad, boletosComprados);
        }
        
        public System.Threading.Tasks.Task<bool> DisminuirDisponibilidadAsync(int codigoPartido, string codigoLocalidad, int boletosComprados) {
            return base.Channel.DisminuirDisponibilidadAsync(codigoPartido, codigoLocalidad, boletosComprados);
        }
    }
}
